### ISSUE TITLE
Can't download live stream.

### ISSUE THREAD

**Issue by pibrizo** [Darkness4/withny-dl#6]
nice to meet you
We truly appreciate your efforts.

I am using Windows 10
withny-dl-windows-amd64-v0.2.11.exe
I used version

However, I cannot use it due to the following error:

![image](https://github.com/user-attachments/assets/2f080e40-d8df-4a19-93d0-23c6d4a518e4)
![image](https://github.com/user-attachments/assets/63c6571e-c1ea-4fc9-bc8c-4d2539dc68ef)

It may be difficult to make an accurate diagnosis based on this alone, so how can you determine what problems are expected?

**Comment by Darkness4** [comment]
I'm going to add more logs. In the meantime, can you try version 1 and see if any new errors occur again?

**Comment by Darkness4** [comment]
Ah wait, I can replicate the issue. Looks like the withny API has changed, I fixing it right now.

**Comment by Darkness4** [comment]
Looks like the playlist API has changed too.

**Comment by Darkness4** [comment]
Ok, actually the GetStreams API has moved from `/streams` to `/streams/with-rooms`.

**Comment by Darkness4** [comment]
Fixed with https://github.com/Darkness4/withny-dl/commit/3b122b7c453e84d1696382e7c64f9e4fc9fb15f4 .

Closing issue.

**Comment by Darkness4** [comment]
Hourly contract testing has been added to notify about API changes.

**Comment by pibrizo** [comment]
Oh Jesus
thank you

I am so happy with the developer’s feedback!!
